create table if not exists public.users (
  user_id bigint generated by default as identity primary key,
  name varchar(100) not null,
  email varchar(255) not null unique,
  password_hash varchar(255),
  created_at timestamptz not null default now()
);

create table if not exists public.courses (
  course_id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(user_id) on delete cascade,
  name varchar(200) not null,
  course_code varchar(50), teacher varchar(100), department varchar(100),
  difficulty varchar(10) not null default 'Medium',
  hours_required double precision not null default 3,
  course_type varchar(20) not null default 'Theory',
  color varchar(7) not null default '#3B82F6',
  credits double precision not null default 3,
  grade varchar(5),
  created_at timestamptz not null default now()
);

create table if not exists public.timetable (
  timetable_id bigint generated by default as identity primary key,
  course_id bigint references public.courses(course_id) on delete cascade,
  user_id bigint not null references public.users(user_id) on delete cascade,
  subject_name varchar(200) not null, course_code varchar(50), teacher varchar(100),
  classroom varchar(100), day varchar(20) not null, start_time varchar(10) not null,
  end_time varchar(10) not null, created_at timestamptz not null default now()
);

create table if not exists public.tasks (
  task_id bigint generated by default as identity primary key,
  course_id bigint references public.courses(course_id) on delete set null,
  user_id bigint not null references public.users(user_id) on delete cascade,
  title varchar(255) not null, description text, deadline timestamptz,
  estimated_time double precision not null default 1,
  difficulty varchar(10) not null default 'Medium',
  status varchar(20) not null default 'Not Started', priority integer not null default 3,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);

create table if not exists public.notes (
  note_id bigint generated by default as identity primary key,
  course_id bigint references public.courses(course_id) on delete set null,
  user_id bigint not null references public.users(user_id) on delete cascade,
  title varchar(255) not null, content text, tags varchar(500),
  is_favourite boolean not null default false, attachments text,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);

create table if not exists public.academic_records (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.users(user_id) on delete cascade,
  semester_name varchar(100) not null, sgpa double precision not null,
  cgpa double precision not null, total_credits double precision not null,
  created_at timestamptz not null default now()
);

create table if not exists public.study_sessions (
  session_id bigint generated by default as identity primary key,
  task_id bigint references public.tasks(task_id) on delete set null,
  user_id bigint not null references public.users(user_id) on delete cascade,
  date date not null, duration double precision not null, notes text,
  created_at timestamptz not null default now()
);

create index if not exists idx_courses_user_id on public.courses(user_id);
create index if not exists idx_timetable_user_id on public.timetable(user_id);
create index if not exists idx_tasks_user_id on public.tasks(user_id);
create index if not exists idx_notes_user_id on public.notes(user_id);
create index if not exists idx_academic_records_user_id on public.academic_records(user_id);
create index if not exists idx_study_sessions_user_id on public.study_sessions(user_id);
